### ISSUE TITLE
pre-trained models and data can not be download via google account in China

### ISSUE THREAD

**Issue by xuershuaigit** [Liumouliu/PlueckerNet#1]
Hi, thanks for your code! however, pre-trained models and data can not be download via google account in China, can I download files in other ways?

**Comment by Liumouliu** [comment]
Try:

1. Apollo
https://cloudstor.aarnet.edu.au/plus/s/klyxxlwXTiMlKMo/download
2. Structured3D and Semantic3D 
https://cloudstor.aarnet.edu.au/plus/s/i7ZGW1R5LgsRNZt/download
3. model
https://cloudstor.aarnet.edu.au/plus/s/2mbws3P3nPoQpIR/download

Best,
liu

**Comment by xuershuaigit** [comment]
Thanks！
